apps/funcionarios/urls.py
from django.urls import path
from .views import (FucionariosList,
                    FucionariosEdit,
                    FuncionarioDelete,
                    FuncionarioNovo
                    )
urlpatterns = [
path('', FucionariosList.as_view(),name='list_funcionarios'),
path('editar/<int:pk>/', FucionariosEdit.as_view(),name='update_funcionario'),
path('novo/', FuncionarioNovo.as_view(),name='create_funcionario'),
path('delete/<int:pk>/', FuncionarioDelete.as_view(),name='deletar_funcionario'),

]

gestao_rh/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
urlpatterns = [
path('', include('apps.core.urls')),
path('funcionarios/', include('apps.funcionarios.urls')),
path('departamentos/', include('apps.departamentos.urls')),
path('documentos/', include('apps.documentos.urls')),
path('horas_extras/', include('apps.registro_hora_extra.urls')),
path('empresa/', include('apps.empresas.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/documentos/models.py
from django.db import models
from django.urls import reverse

from apps.funcionarios.models import Funcionario

class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    pertence = models.ForeignKey(Funcionario,on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')
    #redireciona a url depois de add, e passa o id
    def get_absolute_url(self):
        return reverse('update_funcionario',args=[self.pertence.id])

    def __str__(self):
        return self.descricao

apps/funcionarios/models.py
from django.db import models
#importar user pra funcionarios
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse

from apps.departamentos.models import Departamento
from apps.empresas.models import Empresa


class Funcionario(models.Model):
    nome = models.CharField(max_length=100)
    # CASCADE se remover user remove funcionario, PROTEC da de deletar um por vez
    user = models.OneToOneField(User,on_delete=models.PROTECT)
    departamentos = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT, null=True,blank=True)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('list_funcionarios')

    @property
    def total_de_hora_extra(self):
        return self.registroextra_set.all().aggregate(Sum('horas'))['horas__sum']

apps/registro_hora_extra/models.py
from django.db import models
from django.urls import reverse

from apps.funcionarios.models import Funcionario


class RegistroExtra(models.Model):
    motivo = models.CharField(max_length=100)
    funcionario = models.ForeignKey(Funcionario,on_delete=models.PROTECT)
    horas = models.DecimalField(max_digits=5,decimal_places=2)

    def get_absolute_url(self):
        return reverse('update_funcionario',args=[self.funcionario.id])


    def __str__(self):
        return self.motivo

apps/funcionarios/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import( ListView,
                                  UpdateView,
                                  DeleteView,
                                  CreateView)
from .models import Funcionario


class FucionariosList(ListView):
    model = Funcionario
    #metodo para listar
    def get_queryset(self):
        # pegar funcionario da empresa logada
        empresa_logaga = self.request.user.funcionario.empresa
        return Funcionario.objects.filter(empresa=empresa_logaga)

#atualizar
class FucionariosEdit(UpdateView):
    model = Funcionario
    fields = ['nome','departamentos']

#deletar
class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('list_funcionarios')

class FuncionarioNovo(CreateView):
    model = Funcionario
    fields = ['nome','departamentos']
    #manipular formularios
    def form_valid(self, form):
        funcionario = form.save(commit=False)
        #cria um username concatenando primeiro e segundo nome digitado, split remove os espaços
        username = funcionario.nome.split(' ')[0]+funcionario.nome.split(' ')[1]
        funcionario.empresa = self.request.user.funcionario.empresa#cria uma empresa do mesmo que o usuario logado
        funcionario.user = User.objects.create(username=username)
        funcionario.save()
        return super(FuncionarioNovo, self).form_valid(form)

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Deletar funcionarios{% endblock %}
{% block main %}
<h1>Deletar</h1>
<form method="post">
	{% csrf_token %}
	<h1>Você tem certeza que quer deletar o funcionario {{object}}</h1>
	{{form.as_p}}
	<button type="submit" class="btn btn-danger">Deletar</button>
</form>

{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block title %}Salvar funcionarios{% endblock %}
{% block main %}
<h1>Funcionario</h1>
<form method="post">
	{% csrf_token %}

	{{ form|bootstrap }}
	<br>
	<button type="submit" class="btn btn-primary">Salvar</button>
</form><br>
{% if object %}
<a href="{% url 'create_documentos' object.id  %}"class="btn btn-info">Adicionar documentos</a>
<br>

<h2>Documentos</h2>
	<ul>
		{% for documento in object.documento_set.all %}<br>
		<li>
			<a href="{{documento.arquivo.url}}">{{documento.descricao}}</a>
		</li>
{% endfor %}
</ul>

<br>
<a href="{% url 'create_hora_extra' %}"class="btn btn-info">Criar banco de horas</a>
<h2>Banco de horas</h2>
	<ul>
		{% for horas in object.registroextra_set.all %}<br>
		<li>

			<a href="{% url 'edit_hora_extra' horas.id %}">{{horas.motivo}}/{{horas.horas}}</a>
		</li>
	</ul>
		{% endfor %}


		<h3>Total de horas extras: {{object.total_de_hora_extra}}</h3>
{% endif %}
{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}
{% block title %}Funcionarios{% endblock %}
{% block main %}
<h1>List</h1>
<! – para fazer o loop usar a palavra object_list–>
	{% for funcionario in object_list %}
		<a href="{% url 'update_funcionario' funcionario.id %}">
			{{ funcionario}}
		</a>
		<a href="{% url 'deletar_funcionario' funcionario.id %}">
			deletar
		</a><br>
	{% endfor %}
	<a href="{% url 'create_funcionario' %}" class="btn btn-info">Novo</a>
{% endblock %}